{{- define "discovery.serviceAccountSpec"}}
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.discovery.serviceAccount.extraAnnotations }}
  annotations:
    {{- range $key, $value := .Values.discovery.serviceAccount.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    app: gloo
    gloo: discovery
  name: discovery
  namespace: {{ $.Release.Namespace }}
{{- if .Values.discovery.serviceAccount.disableAutomount }}
automountServiceAccountToken: false
{{ end }}
{{- end }}

{{/* Render template with yaml overrides */}}
{{- $yamlOverride := include "gloo.util.safeAccessVar" (list . ".Values.discovery.serviceAccount.yamlOverride") }}
{{- template "gloo.util.merge" (list . $yamlOverride "discovery.serviceAccountSpec") -}}