{{- define "gatewayProxy.disruptionBudgetSpec"}}
{{- $name := (index . 1) }}
{{- $gatewaySpec := (index . 2) }}
{{- with (first .) }}
{{- $gatewayProxy := .Values.gatewayProxies.gatewayProxy -}}
{{- $spec := deepCopy $gatewaySpec | mergeOverwrite (deepCopy $gatewayProxy) -}}
{{- if $spec.kind.deployment}}
{{- if $spec.podDisruptionBudget }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ $name | kebabcase }}-pdb
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if $spec.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $spec.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if $spec.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $spec.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      gloo: gateway-proxy
{{- end }}
{{- end }}
{{- end }} {{/* with */}}
{{- end }} {{/* define gatewayProxy.deploymentSpec*/}}

{{- if .Values.gateway.enabled }}
{{- range $name, $gatewaySpec := .Values.gatewayProxies }}
{{/* Render each gatewayProxy template with it's yaml overrides */}}
{{- $var := (print ".Values.gatewayProxies." $name ".podDisruptionBudget.yamlOverride") }}
{{- $yamlOverride := include "gloo.util.safeAccessVar" (list $ $var) }}
{{- $ctx := (list $ $name $gatewaySpec)}}
{{- template "gloo.util.merge" (list $ctx $yamlOverride "gatewayProxy.disruptionBudgetSpec") -}}
{{- end }}
{{- end }}